server {
    listen 80;
    server_name kekez.ru www.kekez.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kekez.ru www.kekez.ru;

    ssl_certificate /etc/letsencrypt/live/kekez.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kekez.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /header {
        alias /usr/share/nginx/html/header;
        try_files $uri =404;
    }

    location /footer {
        alias /usr/share/nginx/html/footer;
        try_files $uri =404;
    }

    error_page 404 /404.html;
}